// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestRemoteServer.Models
{
    public partial class CountryRegion
    {
        public CountryRegion()
        {
            Farm = new HashSet<Farm>();
        }

        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string NumCode { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public DateTime CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public bool Deleted { get; set; }

        public virtual ICollection<Farm> Farm { get; set; }
    }
}