// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestRemoteServer.Models
{
    public partial class Farm
    {
        public Farm()
        {
            InverseParentFarm = new HashSet<Farm>();
            Plot = new HashSet<Plot>();
        }

        public int Id { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public decimal? Gpsx { get; set; }
        public decimal? Gpsy { get; set; }
        public DateTime CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public bool Deleted { get; set; }

        public bool WithoutPackHouse { get; set; }

        public int? ParentFarmId { get; set; }
        public int? CountryId { get; set; }
        public long? NoOfReceivedStickers { get; set; }
        public long? NoOfUsedStickers { get; set; }
        public string Remarks { get; set; }
        public DateTime? HarvestDate { get; set; }

        public virtual CountryRegion Country { get; set; }
        public virtual Farm ParentFarm { get; set; }
        public virtual ICollection<Farm> InverseParentFarm { get; set; }
        public virtual ICollection<Plot> Plot { get; set; }
    }
}