// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestRemoteServer.Models
{
    /// <summary>
    /// Per Acre
    /// </summary>
    public partial class Plot
    {
        public int Id { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public int FarmId { get; set; }
        public int? NoOfTree { get; set; }
        /// <summary>
        /// Per Acre
        /// </summary>
        public double? Size { get; set; }
        public DateTime CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public int? ModifiedBy { get; set; }
        public bool Deleted { get; set; }
        public int VarietyId { get; set; }
        /// <summary>
        /// In &quot;Metric Ton&quot;
        /// </summary>
        public double? EstimateWeight { get; set; }
        /// <summary>
        /// Current Weight is the weight which changes in every packing, and must be less than Estimate Weight 
        /// Unit is in &quot;Metric Ton&quot;
        /// </summary>
        public double CurrentWeight { get; set; }
        /// <summary>
        /// If Weight reach MAX, this Grower will be blocked.
        /// The unit of weight is in &quot;Metric Ton&quot;
        /// </summary>
        public double? MaxWeight { get; set; }
        public DateTime? PlantingYear { get; set; }
        public string VineSpacing { get; set; }
        public string Quality { get; set; }
        public string Remarks { get; set; }
        public double? TempEstimateWeight { get; set; }

        public virtual Farm Farm { get; set; }
        public virtual Variety Variety { get; set; }
    }
}