// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestRemoteServer.Models
{
    public partial class Variety
    {
        public Variety()
        {
            Plot = new HashSet<Plot>();
        }

        public int Id { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public DateTime CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string Image { get; set; }
        public int? ModifiedBy { get; set; }
        public bool Deleted { get; set; }
        public string Color { get; set; }

        public virtual ICollection<Plot> Plot { get; set; }
    }
}